"""Added account table

Revision ID: 59351042a324
Revises: 93d2825b110d
Create Date: 2022-09-03 13:27:01.089123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59351042a324'
down_revision = '93d2825b110d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
