"""created transaction model 6

Revision ID: 93d2825b110d
Revises: c91323f8b4ff
Create Date: 2022-09-03 13:16:53.208910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93d2825b110d'
down_revision = 'c91323f8b4ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
