"""created transaction model 3

Revision ID: a08c3fca7f09
Revises: c04e2ed354e3
Create Date: 2022-09-03 13:00:29.924111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a08c3fca7f09'
down_revision = 'c04e2ed354e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
