"""created transaction model 2

Revision ID: c04e2ed354e3
Revises: 89c07d14e84c
Create Date: 2022-09-03 12:58:04.145109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04e2ed354e3'
down_revision = '89c07d14e84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
