"""created transaction model 5

Revision ID: c91323f8b4ff
Revises: a08c3fca7f09
Create Date: 2022-09-03 13:13:53.557233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c91323f8b4ff'
down_revision = 'a08c3fca7f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
